### ISSUE TITLE
Error when processing hexadecimal strings with an odd number of digits

### ISSUE THREAD

**Issue by oleax21** [KaiHiroi/erc7201#1]
## Description
There was a string that was not converted.  
When the recombined hexadecimal string results in an odd number of digits, attempting to further process this odd-digit hexadecimal string can lead to an "Odd number of digits" error.

### Given String
`nftmarketplace.storage.contractaddress`

### Error
`Error: 
Odd number of digits
00`

**Comment by kaihiroi** [comment]
Thank you for reporting this issue!

I have addressed the bug in the following PR:
- #2 

Please review the changes at your convenience.

**Comment by oleax21** [comment]
Thanks for the fix. It worked fine.
